services:
  app:
    build: .
    container_name: contact-monitor-synchronizer_app
    working_dir: /app
    volumes:
      - ./:/app
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    ports:
      - "8080:8000"
    environment:
      PHP_CLI_SERVER_WORKERS: 16
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build: .
    container_name: contact-monitor-synchronizer_worker
    working_dir: /app
    volumes:
      - ./:/app
    command: ["php", "artisan", "queue:work", "--sleep=3", "--tries=1", "--max-time=3600"]
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  scheduler:
    build: .
    container_name: contact-monitor-synchronizer_scheduler
    working_dir: /app
    volumes:
      - ./:/app
    command: ["sh", "-c", "while true; do php artisan schedule:run --no-interaction; sleep 60; done"]
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: contact-monitor-synchronizer_db
    environment:
      POSTGRES_DB: contact-monitor-synchronizer
      POSTGRES_USER: contact-monitor-synchronizer
      POSTGRES_PASSWORD: contact-monitor-synchronizer
    volumes:
      - contact-monitor-synchronizer_pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  contact-monitor-synchronizer_pgdata:
